/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(afsk1200_tx_f.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(9517e260c21449c390e47ef4505b2068)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/afsk1200_tx_f.h>
// pydoc.h is automatically generated in the build directory
#include <afsk1200_tx_f_pydoc.h>

void bind_afsk1200_tx_f(py::module& m)
{

    using afsk1200_tx_f    = ::gr::lilacsat::afsk1200_tx_f;


    py::class_<afsk1200_tx_f, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<afsk1200_tx_f>>(m, "afsk1200_tx_f", D(afsk1200_tx_f))

        .def(py::init(&afsk1200_tx_f::make),
           py::arg("destination"),
           py::arg("source"),
           py::arg("repeater1"),
           py::arg("repeater2"),
           py::arg("padding_zero"),
           D(afsk1200_tx_f,make)
        )
        



        ;




}








