/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(attach_preamble_and_tailer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(687f689050af0e2fd4ac1c669298b8b3)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/attach_preamble_and_tailer.h>
// pydoc.h is automatically generated in the build directory
#include <attach_preamble_and_tailer_pydoc.h>

void bind_attach_preamble_and_tailer(py::module& m)
{

    using attach_preamble_and_tailer    = ::gr::lilacsat::attach_preamble_and_tailer;


    py::class_<attach_preamble_and_tailer, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<attach_preamble_and_tailer>>(m, "attach_preamble_and_tailer", D(attach_preamble_and_tailer))

        .def(py::init(&attach_preamble_and_tailer::make),
           py::arg("len_preamble"),
           py::arg("len_tailer"),
           py::arg("padding_type"),
           D(attach_preamble_and_tailer,make)
        )
        



        ;




}








