/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(file_sink_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c60a5af84d0e60b1cf1544e17530c7fb)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/file_sink_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <file_sink_pdu_pydoc.h>

void bind_file_sink_pdu(py::module& m)
{

    using file_sink_pdu    = ::gr::lilacsat::file_sink_pdu;


    py::class_<file_sink_pdu, gr::block, gr::basic_block,
        std::shared_ptr<file_sink_pdu>>(m, "file_sink_pdu", D(file_sink_pdu))

        .def(py::init(&file_sink_pdu::make),
           py::arg("path"),
           py::arg("format"),
           D(file_sink_pdu,make)
        )
        



        ;




}








