/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(gmsk_demod.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(33b4c7f854852b971c88daed1b72d3cc)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/gmsk_demod.h>
// pydoc.h is automatically generated in the build directory
#include <gmsk_demod_pydoc.h>

void bind_gmsk_demod(py::module& m)
{

    using gmsk_demod    = ::gr::lilacsat::gmsk_demod;


    py::class_<gmsk_demod, gr::block, gr::basic_block,
        std::shared_ptr<gmsk_demod>>(m, "gmsk_demod", D(gmsk_demod))

        .def(py::init(&gmsk_demod::make),
           py::arg("dtll_gain"),
           py::arg("pd_N_avg"),
           py::arg("pd_k1"),
           py::arg("pd_k2"),
           py::arg("vco_gain"),
           D(gmsk_demod,make)
        )
        



        ;




}








