/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(plan13_cc.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ffed107b7dbe85db744300ce62713c0d)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/plan13_cc.h>
// pydoc.h is automatically generated in the build directory
#include <plan13_cc_pydoc.h>

void bind_plan13_cc(py::module& m)
{

    using plan13_cc    = ::gr::lilacsat::plan13_cc;


    py::class_<plan13_cc, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<plan13_cc>>(m, "plan13_cc", D(plan13_cc))

        .def(py::init(&plan13_cc::make),
           py::arg("enable"),
           py::arg("tle1"),
           py::arg("tle2"),
           py::arg("lon"),
           py::arg("lat"),
           py::arg("height"),
           py::arg("fc"),
           py::arg("samp_rate"),
           py::arg("txrx"),
           py::arg("verbose"),
           D(plan13_cc,make)
        )
        



        ;




}








