/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(rs_decode_pdu.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(6f2eac718f94dc1601d7ce64ff4e445e)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/rs_decode_pdu.h>
// pydoc.h is automatically generated in the build directory
#include <rs_decode_pdu_pydoc.h>

void bind_rs_decode_pdu(py::module& m)
{

    using rs_decode_pdu    = ::gr::lilacsat::rs_decode_pdu;


    py::class_<rs_decode_pdu, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<rs_decode_pdu>>(m, "rs_decode_pdu", D(rs_decode_pdu))

        .def(py::init(&rs_decode_pdu::make),
           D(rs_decode_pdu,make)
        )
        



        ;




}








