/*
 * Copyright 2021 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(two_bit_dpd_precoder.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(4cd626a7e92ee75e7bb19dce7fb7dd67)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <lilacsat/two_bit_dpd_precoder.h>
// pydoc.h is automatically generated in the build directory
#include <two_bit_dpd_precoder_pydoc.h>

void bind_two_bit_dpd_precoder(py::module& m)
{

    using two_bit_dpd_precoder    = ::gr::lilacsat::two_bit_dpd_precoder;


    py::class_<two_bit_dpd_precoder, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<two_bit_dpd_precoder>>(m, "two_bit_dpd_precoder", D(two_bit_dpd_precoder))

        .def(py::init(&two_bit_dpd_precoder::make),
           py::arg("init_value"),
           D(two_bit_dpd_precoder,make)
        )
        



        ;




}








